# Generated by Django 5.2.1 on 2025-06-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('source', models.CharField(max_length=100)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('action', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=50)),
                ('details', models.JSONField(default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='logs_logent_timesta_1e81d2_idx'), models.Index(fields=['user'], name='logs_logent_user_a2daaf_idx'), models.Index(fields=['action'], name='logs_logent_action_346979_idx')],
            },
        ),
    ]
